# Lab2 exercises


### 1) create a function that generates a column vector, taking in input a list of numbers
<pre>
cv([1,4,2])
array([[1],
       [4],
       [2]])
</pre>

### 2) Write a function that takes a matrix and returns the transpose of that. You can use 'np.transpose' or the '.T', but you may not use a loop.

### 3) Write a function using NumPy to remove elements from a numpy array identified by an input list
example
<pre>
a=np.array([1,2,3,6,7,9])
b=[2,3]
remov(a,b)
array([1,6,7,9])
</pre>

### 4) Write a NumPy program to test element-wise for NaN of a given array.

### 5) Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

### 6) Write a NumPy program to create an array of all the even integers from 30 to 70

### 7) Write a function using NumPy to generate a random number array between 0 and 1
example
<pre>
randzeroone(3)
[0.73434833 0.40929972 0.48984798]
</pre>

### 8)Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

### 9) Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last

### 10) Write a NumPy program to create a vector of length 100 with values evenly distributed between -10 and 10

### 11) Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15

### 12) Write a NumPy program to multiply the values of two given vectors

### 13) Write a NumPy program to create a 3x4 matrix filled with values from 5 to 16

### 14) Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0

### 15) Write a NumPy program to create a 3x3x3 array filled with arbitrary values


### 16) Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

### 17) Create a matrix of 3x3 with numbers from 1 to 9 and extract the arrays [7,9], [2,5,8] using the correct slicing syntax